import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
  fallback: ["sans"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pl"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="bg-[#FAFAFA]">
        <main className="max-w-318 mx-auto py-6 md:py-13.5 md:px-4">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
